# -*- coding: utf-8 -*-
"""Exercicio Modulo 1 - Calculadora .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UISTt1ue-JSFFZTHja-MuRGi-rOv4HDU

#**Calculadora**#
"""

# Utilize o comando 'input' para receber ao menos 2 números de entrada do usuário;
# Converta os valores recebidos pelo usuário para número inteiro (int) ou ponto flutuante (float);

# Implemente ao menos 4 operações matemáticas em seu código;

# Adicione um laço de repetição ou uma condicional. Por exemplo: você pode permitir que o usuário escolha qual operação realizar ou criar um loop que permita ao usuário realizar várias operações consecutivas;

# Utilize o comando 'print' para exibir o resultado da operação matemática.

escolha_operação=input('Escolha uma operação? (soma/subtração/multiplicação/divisão): ')

num1=float(input('Digite um numero:'))
num2=float(input('Digite um numero:'))

if escolha_operação == 'soma':
    resultado = num1 + num2
    print('O resultado da soma é:', resultado)

elif escolha_operação == 'subtração':
    resultado = num1 - num2
    print('O resultado da subtração é:', resultado)

elif escolha_operação == 'multiplicação':
    resultado = num1 * num2
    print('O resultado da multiplicação é:', resultado)

elif escolha_operação == 'divisão':
   if num2 != 0:
      resultado = num1 / num2
      print('O resultado da divisão é:', resultado)
   else:
      print('Erro: divisão por zero')

else:
  print('Operação invalida.')

